export interface Blog {
  id: string;
  title: string;
  category: string;
  excerpt: string;
  content: string;
  author: string;
  date: string;
  image: string;
  readTime: number;
}

export const CATEGORIES = [
  "Technology",
  "Design",
  "Business",
  "Lifestyle",
  "AI",
];

export const blogs: Blog[] = [
  // Technology Category
  {
    id: "tech-1",
    title: "The Future of Web Development with React 19",
    category: "Technology",
    excerpt:
      "Exploring the groundbreaking features of React 19 and how they revolutionize web development.",
    content: "React 19 brings unprecedented capabilities...",
    author: "Sarah Chen",
    date: "Dec 1, 2025",
    image: "/modern-web-development.png",
    readTime: 8,
  },
  {
    id: "tech-2",
    title: "TypeScript Mastery: Advanced Patterns",
    category: "Technology",
    excerpt:
      "Deep dive into advanced TypeScript patterns that will elevate your coding skills.",
    content: "TypeScript's advanced patterns include...",
    author: "Alex Rodriguez",
    date: "Nov 28, 2025",
    image: "/typescript-code.png",
    readTime: 12,
  },
  {
    id: "tech-3",
    title: "Next.js 15: Performance Upgrades",
    category: "Technology",
    excerpt:
      "Discover how Next.js 15 delivers unprecedented performance improvements.",
    content: "Next.js 15 introduces...",
    author: "Jordan Kim",
    date: "Nov 25, 2025",
    image: "/nextjs-framework.jpg",
    readTime: 10,
  },
  {
    id: "tech-4",
    title: "Serverless Architecture Best Practices",
    category: "Technology",
    excerpt:
      "Learn the best practices for building scalable serverless applications.",
    content: "Serverless architecture requires...",
    author: "Emma Watson",
    date: "Nov 22, 2025",
    image: "/cloud-computing-concept.png",
    readTime: 9,
  },
  {
    id: "tech-5",
    title: "Database Optimization Techniques",
    category: "Technology",
    excerpt:
      "Essential techniques to optimize your database performance and reduce query times.",
    content: "Database optimization starts with...",
    author: "Michael Brown",
    date: "Nov 20, 2025",
    image: "/database-optimization.png",
    readTime: 11,
  },
  {
    id: "tech-6",
    title: "API Design Principles",
    category: "Technology",
    excerpt:
      "Building RESTful APIs that scale and maintain backward compatibility.",
    content: "API design is about...",
    author: "Lisa Park",
    date: "Nov 18, 2025",
    image: "/api-design-concept.png",
    readTime: 7,
  },
  {
    id: "tech-7",
    title: "JavaScript Performance Optimization",
    category: "Technology",
    excerpt:
      "Techniques to write faster JavaScript and improve application performance.",
    content: "JavaScript performance depends on...",
    author: "David Lee",
    date: "Nov 15, 2025",
    image: "/javascript-performance.png",
    readTime: 10,
  },
  {
    id: "tech-8",
    title: "GraphQL vs REST",
    category: "Technology",
    excerpt: "Comparing GraphQL and REST for modern API development.",
    content: "GraphQL offers advantages...",
    author: "Sophie Chen",
    date: "Nov 12, 2025",
    image: "/graphql-logo.png",
    readTime: 8,
  },
  {
    id: "tech-9",
    title: "Docker Containerization Guide",
    category: "Technology",
    excerpt: "Complete guide to containerizing applications with Docker.",
    content: "Docker revolutionizes deployment...",
    author: "James Wilson",
    date: "Nov 10, 2025",
    image: "/docker-containers.jpg",
    readTime: 13,
  },
  {
    id: "tech-10",
    title: "Web Security Essentials",
    category: "Technology",
    excerpt: "Protect your applications with essential web security practices.",
    content: "Web security involves...",
    author: "Rachel Green",
    date: "Nov 8, 2025",
    image: "/cybersecurity-network.png",
    readTime: 9,
  },

  // Design Category
  {
    id: "design-1",
    title: "Design Systems That Scale",
    category: "Design",
    excerpt: "Building design systems that grow with your product and team.",
    content: "Scalable design systems...",
    author: "Marcus Johnson",
    date: "Dec 2, 2025",
    image: "/design-system-abstract.png",
    readTime: 10,
  },
  {
    id: "design-2",
    title: "Color Psychology in UI",
    category: "Design",
    excerpt: "Understanding how colors influence user behavior and emotions.",
    content: "Color psychology reveals...",
    author: "Nina Patel",
    date: "Nov 29, 2025",
    image: "/color-palette-design.png",
    readTime: 7,
  },
  {
    id: "design-3",
    title: "Typography for the Web",
    category: "Design",
    excerpt:
      "Mastering web typography to create readable and beautiful interfaces.",
    content: "Web typography combines...",
    author: "Oliver Hayes",
    date: "Nov 26, 2025",
    image: "/typography-design.png",
    readTime: 8,
  },
  {
    id: "design-4",
    title: "Accessibility First Design",
    category: "Design",
    excerpt: "Creating inclusive designs that work for everyone.",
    content: "Accessibility-first approach...",
    author: "Luna Martinez",
    date: "Nov 23, 2025",
    image: "/accessible-design.png",
    readTime: 11,
  },
  {
    id: "design-5",
    title: "Dark Mode Design Patterns",
    category: "Design",
    excerpt: "Best practices for implementing beautiful dark mode interfaces.",
    content: "Dark mode requires...",
    author: "Alex Turner",
    date: "Nov 21, 2025",
    image: "/dark-mode-ui.jpg",
    readTime: 9,
  },
  {
    id: "design-6",
    title: "Micro-interactions Matter",
    category: "Design",
    excerpt: "How subtle animations enhance user experience.",
    content: "Micro-interactions provide...",
    author: "Grace Liu",
    date: "Nov 19, 2025",
    image: "/animation-design.jpg",
    readTime: 8,
  },
  {
    id: "design-7",
    title: "Mobile-First Design",
    category: "Design",
    excerpt: "Designing responsive interfaces starting with mobile devices.",
    content: "Mobile-first methodology...",
    author: "James Bell",
    date: "Nov 17, 2025",
    image: "/modern-mobile-app-interface.png",
    readTime: 9,
  },
  {
    id: "design-8",
    title: "UX Research Methods",
    category: "Design",
    excerpt: "Conducting effective user research to inform design decisions.",
    content: "User research involves...",
    author: "Sophia Kumar",
    date: "Nov 14, 2025",
    image: "/ux-research-concept.png",
    readTime: 12,
  },
  {
    id: "design-9",
    title: "Figma Best Practices",
    category: "Design",
    excerpt: "Workflow optimization and collaboration tips in Figma.",
    content: "Figma enables...",
    author: "Tom Anderson",
    date: "Nov 11, 2025",
    image: "/figma-design-tool.jpg",
    readTime: 7,
  },
  {
    id: "design-10",
    title: "Design Trends 2025",
    category: "Design",
    excerpt: "The hottest design trends shaping the digital landscape.",
    content: "2025 brings exciting...",
    author: "Victoria Stone",
    date: "Nov 9, 2025",
    image: "/modern-design-trends.jpg",
    readTime: 8,
  },

  // Business Category
  {
    id: "business-1",
    title: "Startup Growth Hacks",
    category: "Business",
    excerpt: "Proven strategies for accelerating your startup's growth.",
    content: "Growth hacking involves...",
    author: "Richard Blake",
    date: "Dec 3, 2025",
    image: "/startup-growth.png",
    readTime: 10,
  },
  {
    id: "business-2",
    title: "Building Remote Teams",
    category: "Business",
    excerpt:
      "Best practices for managing and scaling remote engineering teams.",
    content: "Remote teams require...",
    author: "Catherine White",
    date: "Nov 30, 2025",
    image: "/remote-work-team.png",
    readTime: 9,
  },
  {
    id: "business-3",
    title: "Product-Market Fit",
    category: "Business",
    excerpt:
      "Finding the perfect balance between your product and market demand.",
    content: "Product-market fit is...",
    author: "Marcus Reid",
    date: "Nov 27, 2025",
    image: "/product-development-concept.png",
    readTime: 11,
  },
  {
    id: "business-4",
    title: "Fundraising Essentials",
    category: "Business",
    excerpt: "A comprehensive guide to raising capital for your venture.",
    content: "Fundraising requires...",
    author: "Angela Scott",
    date: "Nov 24, 2025",
    image: "/business-funding.jpg",
    readTime: 13,
  },
  {
    id: "business-5",
    title: "Customer Retention Strategy",
    category: "Business",
    excerpt: "Strategies to keep customers engaged and reduce churn.",
    content: "Customer retention depends on...",
    author: "Brian Zhang",
    date: "Nov 21, 2025",
    image: "/customer-service-interaction.png",
    readTime: 9,
  },
  {
    id: "business-6",
    title: "Data-Driven Decision Making",
    category: "Business",
    excerpt: "Using analytics to make informed business decisions.",
    content: "Data-driven decisions...",
    author: "Diana Foster",
    date: "Nov 19, 2025",
    image: "/data-analytics-visualization.png",
    readTime: 10,
  },
  {
    id: "business-7",
    title: "Marketing Automation",
    category: "Business",
    excerpt: "Streamline your marketing efforts with automation tools.",
    content: "Marketing automation enables...",
    author: "Ethan Moore",
    date: "Nov 16, 2025",
    image: "/marketing-automation-concept.png",
    readTime: 8,
  },
  {
    id: "business-8",
    title: "Business Model Innovation",
    category: "Business",
    excerpt: "Creating innovative business models for competitive advantage.",
    content: "Business model innovation...",
    author: "Fiona Hayes",
    date: "Nov 13, 2025",
    image: "/business-strategy-meeting.png",
    readTime: 11,
  },
  {
    id: "business-9",
    title: "Scaling Operations",
    category: "Business",
    excerpt: "Operational strategies for scaling your business efficiently.",
    content: "Scaling operations requires...",
    author: "Gabriel King",
    date: "Nov 11, 2025",
    image: "/business-operations.jpg",
    readTime: 10,
  },
  {
    id: "business-10",
    title: "Leadership in Tech",
    category: "Business",
    excerpt: "Developing leadership skills essential for tech entrepreneurs.",
    content: "Tech leadership involves...",
    author: "Heather Wells",
    date: "Nov 8, 2025",
    image: "/leadership-business.jpg",
    readTime: 9,
  },

  // Lifestyle Category
  {
    id: "lifestyle-1",
    title: "Remote Work Setup Guide",
    category: "Lifestyle",
    excerpt: "Creating the perfect home office for maximum productivity.",
    content: "A good home office setup...",
    author: "Isabella Grant",
    date: "Dec 1, 2025",
    image: "/home-office-setup.png",
    readTime: 8,
  },
  {
    id: "lifestyle-2",
    title: "Work-Life Balance Tips",
    category: "Lifestyle",
    excerpt:
      "Strategies for maintaining balance between work and personal life.",
    content: "Work-life balance is about...",
    author: "Jason Cole",
    date: "Nov 28, 2025",
    image: "/work-life-balance.png",
    readTime: 7,
  },
  {
    id: "lifestyle-3",
    title: "Productivity Hacks",
    category: "Lifestyle",
    excerpt: "Science-backed techniques to boost your daily productivity.",
    content: "Productivity comes from...",
    author: "Karen Davis",
    date: "Nov 25, 2025",
    image: "/productivity-system.png",
    readTime: 9,
  },
  {
    id: "lifestyle-4",
    title: "Mindfulness for Developers",
    category: "Lifestyle",
    excerpt: "Managing stress and improving mental health as a developer.",
    content: "Developer wellness requires...",
    author: "Leo Martinez",
    date: "Nov 22, 2025",
    image: "/mindfulness-meditation.png",
    readTime: 8,
  },
  {
    id: "lifestyle-5",
    title: "Fitness for Tech Workers",
    category: "Lifestyle",
    excerpt: "Exercise routines designed for people sitting at desks all day.",
    content: "Tech workers need to...",
    author: "Michelle Park",
    date: "Nov 20, 2025",
    image: "/diverse-group-exercising.png",
    readTime: 9,
  },
  {
    id: "lifestyle-6",
    title: "Sleep Optimization",
    category: "Lifestyle",
    excerpt: "Science-based strategies for better sleep and recovery.",
    content: "Good sleep is essential...",
    author: "Nathan Brooks",
    date: "Nov 18, 2025",
    image: "/sleep-wellness.jpg",
    readTime: 7,
  },
  {
    id: "lifestyle-7",
    title: "Nutrition Tips",
    category: "Lifestyle",
    excerpt: "Eating well to maintain energy and focus throughout the day.",
    content: "Nutrition impacts...",
    author: "Olivia Green",
    date: "Nov 15, 2025",
    image: "/healthy-nutrition.png",
    readTime: 8,
  },
  {
    id: "lifestyle-8",
    title: "Travel as a Nomad",
    category: "Lifestyle",
    excerpt: "Living and working remotely while traveling the world.",
    content: "Digital nomad life...",
    author: "Patrick Quinn",
    date: "Nov 12, 2025",
    image: "/digital-nomad-travel.jpg",
    readTime: 10,
  },
  {
    id: "lifestyle-9",
    title: "Learning New Skills",
    category: "Lifestyle",
    excerpt: "Strategies for continuous learning and skill development.",
    content: "Lifelong learning is...",
    author: "Quinn Roberts",
    date: "Nov 10, 2025",
    image: "/learning-development.jpg",
    readTime: 9,
  },
  {
    id: "lifestyle-10",
    title: "Building Community",
    category: "Lifestyle",
    excerpt: "Connecting with others and building meaningful relationships.",
    content: "Community building creates...",
    author: "Rachel Adams",
    date: "Nov 7, 2025",
    image: "/community-networking.jpg",
    readTime: 8,
  },

  // AI Category
  {
    id: "ai-1",
    title: "Generative AI Revolution",
    category: "AI",
    excerpt: "How generative AI is transforming every industry.",
    content: "Generative AI represents...",
    author: "Samuel Cook",
    date: "Dec 4, 2025",
    image: "/artificial-intelligence-network.png",
    readTime: 12,
  },
  {
    id: "ai-2",
    title: "LLM Fine-Tuning Guide",
    category: "AI",
    excerpt: "Step-by-step guide to fine-tuning large language models.",
    content: "Fine-tuning LLMs allows...",
    author: "Tanya Singh",
    date: "Dec 1, 2025",
    image: "/machine-learning-model.jpg",
    readTime: 14,
  },
  {
    id: "ai-3",
    title: "Prompt Engineering Basics",
    category: "AI",
    excerpt: "Master the art of writing effective prompts for AI.",
    content: "Prompt engineering is...",
    author: "Uma Kapoor",
    date: "Nov 29, 2025",
    image: "/ai-chatbot.png",
    readTime: 9,
  },
  {
    id: "ai-4",
    title: "Computer Vision Applications",
    category: "AI",
    excerpt: "Real-world applications of computer vision technology.",
    content: "Computer vision enables...",
    author: "Victor Santos",
    date: "Nov 26, 2025",
    image: "/computer-vision-abstract.png",
    readTime: 11,
  },
  {
    id: "ai-5",
    title: "AI Ethics and Safety",
    category: "AI",
    excerpt: "Responsible AI development and ethical considerations.",
    content: "AI ethics involves...",
    author: "Wendy Chang",
    date: "Nov 23, 2025",
    image: "/ai-ethics-safety.jpg",
    readTime: 10,
  },
  {
    id: "ai-6",
    title: "Neural Networks Explained",
    category: "AI",
    excerpt: "Understanding the fundamentals of neural networks.",
    content: "Neural networks are...",
    author: "Xavier Lopez",
    date: "Nov 21, 2025",
    image: "/placeholder.svg?height=400&width=600",
    readTime: 13,
  },
  {
    id: "ai-7",
    title: "Reinforcement Learning",
    category: "AI",
    excerpt: "Training AI systems through reward-based learning.",
    content: "Reinforcement learning...",
    author: "Yuki Tanaka",
    date: "Nov 18, 2025",
    image: "/placeholder.svg?height=400&width=600",
    readTime: 12,
  },
  {
    id: "ai-8",
    title: "AI for Business Analytics",
    category: "AI",
    excerpt: "Leveraging AI for deeper business insights.",
    content: "Business analytics with...",
    author: "Zara Patel",
    date: "Nov 15, 2025",
    image: "/placeholder.svg?height=400&width=600",
    readTime: 10,
  },
  {
    id: "ai-9",
    title: "Natural Language Processing",
    category: "AI",
    excerpt: "Understanding and processing human language with AI.",
    content: "NLP enables machines...",
    author: "Adrian Wells",
    date: "Nov 12, 2025",
    image: "/placeholder.svg?height=400&width=600",
    readTime: 11,
  },
  {
    id: "ai-10",
    title: "Future of AI",
    category: "AI",
    excerpt: "Exploring the future possibilities and challenges of AI.",
    content: "The future of AI...",
    author: "Bianca Young",
    date: "Nov 10, 2025",
    image: "/placeholder.svg?height=400&width=600",
    readTime: 9,
  },
];

export function getBlogByCategoryAndId(category: string, id: string) {
  return blogs.find((b) => b.category === category && b.id === id) ?? null;
}
